[V3] Dynamic Content
gambitph/Stackable pull request #1313
Opened 2021-07-10 04:06 UTC by blankart

2021-07-19 12:14 UTC, blankart commented on src/components/image-control2/editor.scss
> +			}
the component is not using `disabled` class already. revert the changes

2021-07-19 12:14 UTC, blankart commented on src/components/image-control2/editor.scss
> +			width: 50px;
check if this is still needed

2021-07-19 12:16 UTC, blankart commented on src/components/dynamic-content-control/index.js
> +							description={ __( 'Sample Description.', i18n ) }
update the text

2021-07-20 07:15 UTC, bfintal requested changes
Some feedback
1. I'm seeing some React warnings like `Warning: React does not recognize the `isDynamic` prop on a DOM element`
2. When I create a new page, add a title, add a new adv. heading block, then set the attribute to Current Post > Post Title, it doesn't display the title I just inputted. It shows "Auto Draft"
3. As with 2 above, this also happens when you create a new page, assign a featured image, then immediately use the featured image in the a dynamic content.

Regarding points 2 & 3, the current behavior looks like the dynamic fields data at least for the current post are prepared ahead of time, and aren't refreshed

2021-07-20 10:10 UTC, blankart commented
> Some feedback
> 
> 1. I'm seeing some React warnings like `Warning: React does not recognize the `isDynamic` prop on a DOM element`
> 2. When I create a new page, add a title, add a new adv. heading block, then set the attribute to Current Post > Post Title, it doesn't display the title I just inputted. It shows "Auto Draft"
> 3. As with 2 above, this also happens when you create a new page, assign a featured image, then immediately use the featured image in the a dynamic content.
> 4. For content text controls, when you use dynamic content alongside static text, e.g. `<span ...>My Title</span> Blahblah`, the input control should display `Post Title Blahblah`. Right now it just displays `Post Title`
> 
> Regarding points 2 & 3, the current behavior looks like the dynamic fields data at least for the current post are prepared ahead of time, and aren't refreshed

I will address the react warnings.

Regarding #2, this is the current behavior of our Dynamic Content. all fetching of data comes from our API, thus returning the currently saved data from the database. The current post title won't be shown unless the page was already published. Same with #3.

Regarding #3, it was already discussed that when a dynamic content is present, only the field name will be shown inside the text input. If there's more than one, the field names will be separated by a comma (`,`)

2021-07-21 02:12 UTC, blankart commented
Need to introduce another API for dynamic content resolvers inside the editor

2021-07-22 10:26 UTC, merged