[V3] Icon Block
gambitph/Stackable pull request #1383
Opened 2021-07-27 08:20 UTC by blankart

2021-07-28 10:55 UTC, bfintal commented on src/block-components/icon/attributes.js
> +
It's okay to include all the attributes since it won't have any effect in the block (except if there are any conflicts)

2021-07-28 11:19 UTC, bfintal requested changes
- [x] Adding an icon block, saving it then refreshing the editor results in an error. Based on the error, it's as if the svg wasn't saved.
- [x] When you turn on the shape outline, it should show a color and have a default width. right now when you turn it on, nothing happens.
- [x] When you open the background shape panel, a warning shows up "Warning: React does not recognize the `hasDefault` prop on a DOM element."
- [x] Changing the background shape opacity, saving and reloading will result in a block error
- [x] the default shape outline width should look empty - you shouldn't be able to reset it:
![image](https://user-images.githubusercontent.com/1033611/127367279-ef148af2-9180-4816-a8aa-e832dde7a573.png)
- [x] Add an `aria-hidden="true"` on the svg and remove the `role="img"`
- [x] Add an "Accessibility" panel in the Advanced tab, containing a label. When the label is provided, add it in the svg `role="img" aria-label="Description of your SVG image"` (and then remove `aria-hidden="true"`)

2021-07-29 03:51 UTC, blankart commented
I can't reproduce the 1st issue

2021-07-30 13:48 UTC, bfintal commented on src/block-components/icon/edit.js
> +						max={ 50 }
```suggestion
						sliderMax={ 50 }
```

2021-07-30 13:53 UTC, bfintal commented on src/block-components/icon/edit.js
> +						max={ 100 }
```suggestion
						sliderMax={ 100 }
```

2021-07-30 13:54 UTC, bfintal commented on src/block-components/icon/edit.js
> +						max={ 3 }
```suggestion
						sliderMax={ 3 }
```

2021-07-30 13:55 UTC, bfintal commented on src/block-components/icon/edit.js
> +						max={ 99 }
```suggestion
```

2021-07-30 13:55 UTC, bfintal commented on src/block-components/icon/edit.js
> +						max={ 30 }
```suggestion
						sliderMin={ -30 }
						sliderMax={ 30 }
```

2021-07-30 13:55 UTC, bfintal commented on src/block-components/icon/edit.js
> +						max={ 30 }
```suggestion
						sliderMin={ -30 }
						sliderMax={ 30 }
```

2021-07-30 13:56 UTC, bfintal commented on src/block-components/icon/edit.js
> +					sliderMin={ 0 }
```suggestion
```

2021-07-30 13:56 UTC, bfintal commented on src/block-components/icon/edit.js
> +						sliderMin={ 0 }
```suggestion
						min={ 0 }
```

2021-07-30 14:26 UTC, merged