[V3] Add `stackable/` blocks support for `get_the_excerpt` API
gambitph/Stackable pull request #1414
Opened 2021-07-30 10:13 UTC by blankart

2021-07-31 02:09 UTC, bfintal requested changes
Please see some of my comments in #1413

To make v3 and v2 code separated:
- keep all the `stackable/*` blocks in `src/blocks.php`, then 
- all the old `ugb/*` blocks, move to `src/deprecated/v2/blocks.php`
  - to make things easily searchable, the v2 code, use the function names `excerpt_allowed_wrapper_blocks_v2` and `stackable_add_excerpt_blocks_v2`

2021-08-02 06:07 UTC, blankart commented
I haven't tested my recent commit yet. I am getting a build error in v3 branch:

pro__premium_only 
```
Error: PostCSS plugin autoprefixer requires PostCSS 8
```

Will mark as ready for review once this is resolved.

2021-08-02 07:51 UTC, bfintal requested changes

2021-08-02 07:51 UTC, bfintal commented on src/blocks.php
> +			array_push( $allowed_stackable_wrapper_blocks, 'stackable/' . $stk_wrapper_block );
Don't use the folder names directly as the name of the block, these may be different from the actual block name. Maybe you can refactor the code above that gathers the block meta data `$metadata = json_decode( file_get_contents( $block_json_file ), true );` to get the block name `$metadata['name']`

2021-08-04 01:34 UTC, merged