Feat: Spacer Block
gambitph/Stackable pull request #1423
Opened 2021-08-03 03:36 UTC by blankart

2021-08-03 07:39 UTC, blankart commented on src/block/spacer/style.js
> +		},
```suggestion
			attrName: 'height',
			format: '%spx',
			responsive: 'all',			
		},
```

2021-08-04 07:25 UTC, bfintal requested changes
When you insert the block, the block has 0 height. It should default to `50px`

2021-08-04 09:04 UTC, bfintal requested changes
1. The resizer should only be visible when the block is hovered on
2. When the resizer is dragged and you save the post, refreshing the editor will show an error

2021-08-06 12:52 UTC, bfintal requested changes
A few more things that we should add:
- [x] Our image block snaps to specific widths (multiples of 50px) when resizing, we should add this here as well
- [x] When resizing, there is no indicator of the current size of the spacer, it might be a good idea to add a tooltip similar to the image block too that's visible when hovering over the spacer block

2021-08-10 11:15 UTC, bfintal requested changes
Some comments:
- [ ] The orange color when dragging looks off, make it transparent
- [ ] When you change the height, if you preview in tablet and mobile, the height goes back to default in the editor (works okay in frontend)
- [ ] The popup height shows the reset button when it's already at the default value. Either the reset button shouldn't be there when the value is the default, or the value should show blank when it's the default to prevent the reset button from showing up

2021-09-01 08:13 UTC, merged