Feat: Icon Button Block
gambitph/Stackable pull request #1425
Opened 2021-08-03 08:14 UTC by blankart

2021-08-04 05:33 UTC, blankart commented on src/block/button/style.scss
> +			border-width: 2px;
```suggestion
			border-width: cssvar(button-ghost-border-width);
```

2021-08-04 09:53 UTC, bfintal requested changes
- [x] Move the icon color to the Button Colors panel
- [x] Move the Icon panel immediately after the Button Colors panel
- [x] Also add "Button Width" below "Min. Button Height"
- [x] Add the Styles panel similar to the Button block

2021-08-06 13:08 UTC, bfintal requested changes
- [x] I noticed that there are a lot of repeated styles in the `style.scss` of the button block and the icon button block, these should be shared to lessen the amount of styles we have
- [x] The button inner span previously had the class `stk-button__inner-text` which now became `stk-block-button__inner-text`. We should turn it back since the button text has lost some of its styling. The button class names should be shared between the button block and the icon button block to simplify things.

2021-08-09 13:32 UTC, bfintal commented on src/styles/block.scss
> +}
Please move all `cssvar` and design system related styles in `block-design-system.scss`

2021-08-09 13:35 UTC, bfintal commented on src/block/icon-button/style.scss
> +	text-align: center;
these came from the button block, are these styles needed here?

2021-08-09 13:36 UTC, bfintal commented on src/block/icon-button/style.scss
> +		border-radius: 24px;
We can make this `100%` so that the block remains circular when adjusting the icon size
```suggestion
		border-radius: 100%;
```

2021-08-09 13:38 UTC, bfintal commented on src/block/button/style.scss
>  	text-align: center;
I checked this, if I remove them they don't seem to do anything. Do we still need these styles?

2021-08-10 11:08 UTC, merged