Fix: fixes automatic clamping of values in WP 5.5
gambitph/Stackable pull request #1599
Opened 2021-09-15 09:10 UTC by blankart

2021-09-15 17:25 UTC, bfintal requested changes
In the new refactored code, `setValue( props.value )` will never be called. Is this intended in this change?

2021-09-15 23:47 UTC, blankart commented
> In the new refactored code, `setValue( props.value )` will never be called. Is this intended in this change?

Yes

2021-09-16 02:37 UTC, blankart commented on plugin.php
> + * Version: 3.0.0-beta3-range-control-wp55-fix
```suggestion
 * Version: 3.0.0-beta3
```

2021-09-16 02:38 UTC, blankart commented on plugin.php
> +defined( 'STACKABLE_VERSION' ) || define( 'STACKABLE_VERSION', '3.0.0-beta3-range-control-wp55-fix' );
```suggestion
defined( 'STACKABLE_VERSION' ) || define( 'STACKABLE_VERSION', '3.0.0-beta3' );
```

2021-09-16 05:51 UTC, bfintal commented on src/components/advanced-range-control/range-control.js
> +		} else if ( numberControlRef.current !== document.activeElement ) { // eslint-disable-line
```suggestion
		// Only allow updating of the local state if the number control is not in focus.
		// We do this so the clamping of values will not get triggered as long as the
		// user is typing inside the number control. This happens in WP 5.5
		} else if ( numberControlRef.current !== document.activeElement ) { // eslint-disable-line
```

2021-09-16 05:52 UTC, merged