Fix: Image Border Radius adjusted to 100
gambitph/Stackable pull request #1670
Opened 2021-09-28 10:30 UTC by blankart

2021-09-28 13:32 UTC, bfintal requested changes
The max should change depending on the width or height, whichever is higher

2021-09-29 00:10 UTC, blankart commented
> The max should change depending on the width or height, whichever is higher

There are units in both height and width. Border radius is strictly px

2021-09-29 09:21 UTC, bfintal commented
> There are units in both height and width. Border radius is strictly px

We can use the max value of the width and height whichever is in `px`. Then is both are not `px`, then use `100` instead.

2021-09-30 11:17 UTC, bfintal commented on src/block-components/image/edit.js
> +		return 50
```suggestion
		return 100
```

2021-09-30 11:19 UTC, bfintal commented on src/block-components/image/edit.js
> +			attributes.imageWidthUnit === 'px' &&
```suggestion
			[ '', 'px' ].includes( attributes.imageWidthUnit ) &&
```

2021-09-30 11:19 UTC, bfintal commented on src/block-components/image/edit.js
> +			( [ '', 'px' ].includes( attributes.imageHeightUnit ) )
```suggestion
			[ '', 'px' ].includes( attributes.imageHeightUnit )
```

2021-09-30 11:20 UTC, bfintal commented on src/block-components/image/edit.js
> +			[ '', 'px' ].includes( attributes.imageWidthUnit ) &&
```suggestion
			attributes.imageWidthUnit === 'px' &&
```

2021-09-30 11:24 UTC, merged