Fix/2305 stackable setting missing blocks
gambitph/Stackable pull request #2413
Opened 2022-09-07 05:54 UTC by vmc08

Fixes #2305

2022-09-18 21:37 UTC, bfintal requested changes
We'll need to remove "Button Group" from the getting started and activate/deactivate list because there's really no way to add one by itself without adding a button or an icon button.

2022-10-10 01:30 UTC, andeng1106 commented
**Issue:**
- When disabling Button and Icon Button block, it still shows in block inserter and when using the /

https://user-images.githubusercontent.com/103395655/194788945-4ff9c1d8-27b6-41d1-aa9c-c132077374a4.mp4

**Question:**
- Load More and Pagination button seems to be still missing. Is it expected not to be included?

@vmc08 @bfintal

2022-10-11 08:23 UTC, andeng1106 commented
@vmc08 Tried the new build, the same issue still happens on my end.

2022-10-12 01:49 UTC, bfintal commented
> * Load More and Pagination button seems to be still missing. Is it expected not to be included?

@andeng1106 Let's do this in a separate issue instead

2022-10-21 03:23 UTC, bfintal commented on src/welcome/admin.js
> +export const getAllBlocks = () => applyFilters( 'stackable.settings.merge-blocks', FREE_BLOCKS )
```suggestion
export const getAllBlocks = () => applyFilters( 'stackable.settings.blocks', FREE_BLOCKS )
```

2022-10-21 03:26 UTC, merged