Try performance improvements on style generation
gambitph/Stackable pull request #2446
Opened 2022-10-12 16:53 UTC by bfintal

2022-11-25 12:43 UTC, kmgalanakis requested changes
Regarding Toolset I'm still checking how this works, but for sure we are going to need the `attributes` argument for the `*.edit` filters. Thank you

2022-11-25 12:43 UTC, kmgalanakis commented on src/block-components/container-div/index.js
> +	const uniqueContainerClass = applyFilters( 'stackable.container-div.uniqueClass.edit', `${ uniqueBlockClass }-container`, uniqueBlockClass )
Same here, you most probably forgot to also pass the attributes as a filter argument.

2022-11-25 12:43 UTC, kmgalanakis commented on src/components/block-css/index.js
> +	output = applyFilters( 'stackable.block-styles.edit', output, getUniqueBlockClass( attributes.uniqueId ) )
Same here, you most probably forgot to also pass the attributes as a filter argument.

2022-11-25 12:43 UTC, kmgalanakis commented on src/block-components/block-div/index.js
> +	uniqueBlockClass = applyFilters( 'stackable.block-div.uniqueClass.edit', uniqueBlockClass )
Here you most probably forgot to also pass the attributes as a filter argument.

2022-12-02 06:50 UTC, bfintal commented
> Regarding Toolset I'm still checking how this works, but for sure we are going to need the `attributes` argument for the `*.edit` filters. Thank you

Hey @kmgalanakis thanks for checking this out! The `attributes` object wasn't intentionally passed on the **edit** side in order to prevent component re-renderings. Instead, the `attributes` object now only contains attributes needed by the current component - e.g. the ones needed for container styles in the Container component - so it doesn't have all the attributes of the block.

For the reliable `attributes` object from the within the hook, I'd like to recommend this instead:

```js
const { clientId } = wp.blockEditor.useBlockEditContext()
const attributes = wp.data.select( 'core/block-editor' ).getBlockAttributes( clientId )
```

2022-12-05 13:39 UTC, DAnn2012 commented
Hello @bfintal @vmc08  @prconcepcion 

as soon as you can, could you take a look at these PR #2472 #2498 ?

I think these changes are important and urgent for users who are not using English-language WordPress.

Thanks.

2023-01-04 14:04 UTC, bfintal commented
> > Regarding Toolset I'm still checking how this works, but for sure we are going to need the `attributes` argument for the `*.edit` filters. Thank you
> 
> Hey @kmgalanakis thanks for checking this out! The `attributes` object wasn't intentionally passed on the **edit** side in order to prevent component re-renderings. Instead, the `attributes` object now only contains attributes needed by the current component - e.g. the ones needed for container styles in the Container component - so it doesn't have all the attributes of the block.
> 
> For the reliable `attributes` object from the within the hook, I'd like to recommend pulling the block's attributes instead:
> 
> ```js
> const { clientId } = wp.blockEditor.useBlockEditContext()
> const attributes = wp.data.select( 'core/block-editor' ).getBlockAttributes( clientId )
> ```

Hey @kmgalanakis just checking up whether this change is good for your end.

2023-01-04 14:09 UTC, kmgalanakis commented
@bfintal, what you wrote in that comment made perfect sense and served the purpose of what I needed back then.

Though, I'm no longer working on this project because I'm not part of OnTheGoSystems anymore. You can reach out to them to discuss how to proceed with this.

Thank you.

2023-01-04 14:11 UTC, bfintal commented
@kmgalanakis thanks! I'll reach out to them and ask about it :)

2023-01-17 10:09 UTC, merged