fix (countdown-block): refactored initialization to prevent DOM query selector issues and changed desription.
gambitph/Stackable pull request #2586
Opened 2023-02-13 06:27 UTC by prconcepcion

2023-02-13 07:46 UTC, prconcepcion commented
Fixes https://github.com/gambitph/Stackable/issues/2585

2023-02-21 09:28 UTC, bfintal commented on src/block/countdown/block.json
> +	"description": "Display a countdown timer on your website. This is a great tool for promoting limited-time offers, creating urgency for events, and more.",
```suggestion
	"description": "Display a countdown timer on your website.",
```

2023-02-21 09:29 UTC, bfintal commented on src/block/countdown/divider.js
> +import { i18n } from 'stackable'
Please move this to the external dependencies list.

2023-02-21 09:30 UTC, bfintal requested changes
Just one minor change. After adjusting it, please move this to QA review

2023-02-22 01:43 UTC, andeng1106 commented
Issue (for confirmation):

Some text are not yet translated
- Style > General - this hasn't been translated yet
![image](https://user-images.githubusercontent.com/103395655/220497948-7fc5a7a2-fe3f-4e21-8a0f-97cca7aa401f.png)
![image](https://user-images.githubusercontent.com/103395655/220498031-467b9ce5-b2dd-4914-a816-f9293386c70b.png)

- Style > Labels - other text that has been translated before is no longer being translated
    - Hours & Minutes is no longer translated in the screenshot
![image](https://user-images.githubusercontent.com/103395655/220498331-975ec7f2-dcb8-44d9-8a38-fff73bce7e2c.png)
    - Compared to DAnn2012's screenshot: 
![image](https://user-images.githubusercontent.com/103395655/220498455-ff615e1b-29d9-45c8-87b9-e549d25fd563.png)

@prconcepcion @bfintal

2023-02-23 11:03 UTC, merged