fix: addresses accessibility warning in expand/show more block and accordion block
gambitph/Stackable pull request #2692
Opened 2023-06-07 04:04 UTC by mxkae

fixes #2617 

- removed custom attributes aria-expanded in Expand / Show More block

2023-06-13 23:50 UTC, andeng1106 commented
@mxkae Issue has been fixed for v3 blocks 😁

Remaining issues:
1. V3 Expand / Show More causes a block error when updating build from 3.8.2 (latest) to PR build

- This only happens for existing/old block. New blocks added doesn't cause an issue.

https://github.com/gambitph/Stackable/assets/103395655/551cc09c-22fc-4dbb-975c-7892240e68ad

2. Fix is not yet applied for v2 Accordion & Expand / Show More blocks (for confirmation w/ @bfintal)

2023-06-14 08:09 UTC, bfintal commented on src/block/expand/schema.js
>  		versionDeprecated: '',
```suggestion
		versionDeprecated: '3.9.0',
```

2023-06-15 09:50 UTC, bfintal commented on src/block/expand/edit.js
> +		customAttributes: [ [ 'aria-hidden', 'false' ], [ 'role', 'button' ], [ 'aria-expanded', 'true' ] ],
You are going to click this button to "show more", so this should be `aria-expanded` `false`
```suggestion
		customAttributes: [ [ 'aria-hidden', 'false' ], [ 'role', 'button' ], [ 'aria-expanded', 'false' ] ],
```

2023-06-15 09:51 UTC, bfintal commented on src/block/expand/edit.js
> +		customAttributes: [ [ 'aria-hidden', 'true' ], [ 'role', 'button' ], [ 'aria-expanded', 'false' ] ],
Just like the above, this should be `true`
```suggestion
		customAttributes: [ [ 'aria-hidden', 'true' ], [ 'role', 'button' ], [ 'aria-expanded', 'true' ] ],
```

2023-06-15 09:58 UTC, bfintal commented on src/block/expand/schema.js
> +		versionDeprecated: '3.9.0',
```suggestion
		versionDeprecated: '3.9.1',
```

2023-06-15 09:58 UTC, bfintal requested changes
Please see my comments

2023-06-16 02:48 UTC, andeng1106 commented
No block error anymore when updating builds.

Remaining issue:
- The ARIA warning for Expand / Show More block showed in PageSpeed Insights:
<img width="991" alt="Screenshot 2023-06-16 at 10 37 30 AM" src="https://github.com/gambitph/Stackable/assets/103395655/c288641b-2cba-417a-a6e6-f65c7f7f59b4">
 
@mxkae

2023-06-23 07:14 UTC, bfintal commented
@andeng1106 does this pagespeed issue appear with old blocks or newly created blocks? If it's old, we might need to add some deprecation to remove any existing `aria-expanded` custom attributes

2023-06-25 23:19 UTC, andeng1106 commented
> @andeng1106 does this pagespeed issue appear with old blocks or newly created blocks? If it's old, we might need to add some deprecation to remove any existing `aria-expanded` custom attributes

This happens with old blocks and newly created blocks. @bfintal

2023-06-30 17:40 UTC, merged