feat (size-unit): added VW as a choice among width units
gambitph/Stackable pull request #2765
Opened 2023-07-20 11:35 UTC by prconcepcion

fixes #2735

2023-07-21 02:33 UTC, bfintal requested changes
I don't think these are the only units that can have `vw` and `vh`. If you do a regex search across all JS files, you'll find a number of possible options that can have these new units. Do this search:

```
\[ '(px|%)',
```

2023-07-25 06:53 UTC, andeng1106 commented
@prconcepcion Remaining issue/s:
- Card block - Width is added for Card Image which originally isn't there. Is this intended? @bfintal 
   - Before, Height is the only setting for the Card Image. 
   
<img width="277" alt="Screenshot 2023-07-25 at 2 42 45 PM" src="https://github.com/gambitph/Stackable/assets/103395655/68ab2ce4-dd65-4d06-a030-1a9d6e859f9b">

- Card block - Height is now missing
<img width="280" alt="Screenshot 2023-07-25 at 2 43 19 PM" src="https://github.com/gambitph/Stackable/assets/103395655/0806c7da-9b7f-470b-b202-2f5d95df1478">
   - Now it's applying like this (width) vs. height:
    https://github.com/gambitph/Stackable/assets/103395655/ef0c3f71-d3ae-4ead-863c-430a1b51ecb8

- Carousel block - Arrows > Button Width doesn't have a vw option
<img width="284" alt="Screenshot 2023-07-25 at 2 47 41 PM" src="https://github.com/gambitph/Stackable/assets/103395655/bb1e96bd-3065-484a-bad3-6635ae0ad44f">

2023-07-26 02:46 UTC, andeng1106 commented
@prconcepcion Cannot select vw on Image resizer:

https://github.com/gambitph/Stackable/assets/103395655/13dce078-5b03-4779-b459-a534269a6a0d

2023-07-27 06:42 UTC, bfintal requested changes

2023-07-27 06:42 UTC, bfintal commented on src/block/card/edit.js
> +						heightUnit={ blockStyle !== 'horizontal' ? props.attributes.imageHeightUnit : '%' }
There needs to be a fallback here just incase the attribute is not available

2023-07-27 12:09 UTC, andeng1106 commented
Remaining issue:
When adding a new Card block > Horizontal layout, it's not Horizontal in editor. But upon saving page and viewing frontend, it's correct.

https://github.com/gambitph/Stackable/assets/103395655/c1f9cea4-1881-4057-b315-71c723611b8d

@prconcepcion

2023-07-28 07:45 UTC, merged