fix: add has polyfill for alignment
gambitph/Stackable pull request #2814
Opened 2023-08-07 12:11 UTC by mxkae

fixes #2784

2023-08-07 13:25 UTC, bfintal requested changes
I took the liberty of changing some file/script/class names to better reflect the purpose of the newly introduced script.

I have some remaining suggestions / improvements:

1. We can have better names for the new classes that can signify that they are polyfill classes:
- `stk--height-100` ➡️ `stk--height-100-polyfill`
- `stk-container--has-child-column-flex` ➡️ `stk-container--has-child-column-flex-polyfill`

2. Bring back the specificity of the original selectors you're trying to polyfill, because if not the styles might not be applied correctly.

You're mainly trying to add a class that would have the same effect as the following selectors. But these 2 sets of selectors have different specificities (you can check here: https://specificity.keegan.st/)

- `:is(.stk-block-content, .stk-inner-blocks):not(.stk--column-flex):has(> :is(.stk--block-margin-top-auto, .stk--block-margin-bottom-auto))` ➡️ 3
- `.stk-container:has(> .stk--column-flex)` ➡️ 2

The new selectors are just:

- `.stk--height-100` ➡️ 1
- `.stk-container--has-child-column-flex` ➡️ 1

That means the styles might get easily overridden by other selectors. You'll need to mimic / bump up the specificity to the same level.

2023-08-07 13:25 UTC, bfintal commented on src/block-components/alignment/frontend-has-polyfill.js
> +				const columnFlex = container.querySelector( '.stk--column-flex' )
Based on the selector we're trying to mimic, we need this to be for the direct descendent
```suggestion
				const columnFlex = container.querySelector( ':scope > .stk--column-flex' )
```

2023-08-07 13:25 UTC, bfintal commented on src/block-components/alignment/frontend-has-polyfill.js
> +					container.classList.remove( 'stk-container--has-child-column-flex' )
Do you still need this?

2023-08-08 02:21 UTC, andeng1106 commented
@mxkae @bfintal Fixes are not working in editor for Firefox browser only

some features & scenarios tried:
* innerBlockJustify setting
* innerBlockAlign setting (Inner Column)
* in the inner column block, align all blocks to the left, then the last child block make margin left auto - the last child block should go to the right

2023-08-08 04:50 UTC, bfintal requested changes
I feel it's odd that `Chrome/` is part of the detection for Safari. It should be `Safari/` and `Version/` and the number after version should be <= `15.3`

2023-08-08 05:20 UTC, bfintal commented on src/block-components/alignment/index.php
> +		if ( stripos( $user_agent, 'Version/' ) && stripos( $user_agent, 'Safari/' ) !== false ) {
```suggestion
		if ( stripos( $user_agent, 'Version/' ) !== false && stripos( $user_agent, 'Safari/' ) !== false ) {
```

2023-08-08 05:43 UTC, merged