feat (image): add image through url and add captions to an image
gambitph/Stackable pull request #2889
Opened 2023-09-05 01:10 UTC by prconcepcion

fixes #2873, fixes #2875

2023-09-07 07:39 UTC, bfintal requested changes

2023-09-07 07:39 UTC, bfintal commented on src/block-components/image/index.js
> +		figcaptionClasses={ props.figcaptionClasses }
I think you mean `figcaptionClassnames`
```suggestion
		figcaptionClassnames={ props.figcaptionClasses }
```

2023-09-07 07:39 UTC, bfintal commented on src/block-components/image/index.js
> +		figcaptionClasses={ props.figcaptionClasses }
I think you mean `figcaptionClassnames`
```suggestion
		figcaptionClassnames={ props.figcaptionClasses }
```

2023-09-07 07:39 UTC, bfintal commented on src/block-components/image/image.js
> +			( <Wrapper className={ props.blockName === 'stackable/image' ? undefined : imageWrapperClasses }>
you might need to change this also

2023-09-07 07:39 UTC, bfintal commented on src/block-components/image/image.js
> +
Don't forget to remove this

2023-09-07 07:39 UTC, bfintal commented on src/block/image/deprecated.js
> +addFilter( 'stackable.image.save.wrapper', 'stackable/newWrapper', ( output, imageWrapperClasses, version, notImageBlock, Wrapper, blockName ) => {
It's odd that you're padding `notImageBlock` here. `notImageBlock` should be removed from the block component

2023-09-07 07:39 UTC, bfintal commented on src/block/image/edit.js
> +					figcaptionClasses={ figcaptionClasses }
```suggestion
					figcaptionClassnames={ figcaptionClasses }
```

2023-09-18 09:01 UTC, bfintal requested changes
Some recommendations and comments:
- The background image url should be responsive, they can set a different value for tablet or mobile (so they can mix things e.g. uploaded image for desktop, then typed in url for mobile). For non-background images, it's okay for it to be non-responsive
- If you don't have an image, the caption do not show up
- Add a placeholder for the caption
- Caption is not showing in frontend

2023-10-04 03:59 UTC, bfintal requested changes
Some findings:
- Adding an image URL in a background doesn't show the background image options. If you pick an image from the media manager from the upload button, it will show additional background image options - entering an image url should also show the same.
- Adding a background image URL doesn't work if you have a background gradient. Looks like the styles are added differently - if you try adding a background image using the upload button, it shows the gradient correctly.

2023-10-09 05:35 UTC, andeng1106 commented
Additional issues found:
- #2875
  - When Image block is inside an Accordion block and I enabled Container for the accordion content area, added a text color for Parent Hovered state, it doesn't show the color upon hovering. (issue in editor only)
  Here's a vid, comparing Image caption with a Text block:

https://github.com/gambitph/Stackable/assets/103395655/bc4548b4-7025-421e-af91-302cf87f6d2d

2023-10-24 09:13 UTC, andeng1106 commented
Remaining issues for https://github.com/gambitph/Stackable/issues/2873:

- [ ]  Image block - No preview in Focal Point:

https://github.com/gambitph/Stackable/assets/103395655/cb950128-b831-4767-9c22-49c2b0601659

- [ ] When uploading Background image on all responsive views and use both (uploaded image on desktop > url image on desktop & uploaded image on tablet & mobile), it doesn't show properly on **editor only**
    - Example scenario: Added an image url on desktop & uploaded image on tablet & mobile. It doesn't show the uploaded image on tablet & mobile.
  

https://github.com/gambitph/Stackable/assets/103395655/00e10f1e-e784-4075-9819-9def0c67a6c2

- [ ] When adding Background Image URL, Background panel doesn't automatically enable
   - Related to: https://github.com/gambitph/Stackable/issues/2673
 
@prconcepcion

2023-10-27 00:58 UTC, prconcepcion commented
@bfintal the last 2 commits are related to what we have talked about yesterday

2023-10-27 07:02 UTC, bfintal requested changes

2023-10-27 07:02 UTC, bfintal commented on src/components/block-css/index.js
> +		}
This looks unnecessarily repeated. I would recommend just having `hasDesktop` to be true if `responsive === false`

2023-10-27 15:00 UTC, andeng1106 commented
Remaining issue 1 & 2 has been fixed. This one hasn't been included in the fix yet but might be a good suggestion. Should we not fix this for now? @bfintal 
> * [ ]  When adding Background Image URL, Background panel doesn't automatically enable
>   
>   * Related to: [When adding a background image or background color, auto-enable hasBackground #2673](https://github.com/gambitph/Stackable/issues/2673)
> 
>

2023-10-28 12:07 UTC, bfintal commented
> Remaining issue 1 & 2 has been fixed. This one hasn't been included in the fix yet but might be a good suggestion. Should we not fix this for now? @bfintal 
> 
> > * [ ]  When adding Background Image URL, Background panel doesn't automatically enable
> 
> >   
> 
> >   * Related to: [When adding a background image or background color, auto-enable hasBackground #2673](https://github.com/gambitph/Stackable/issues/2673)
> 
> > 
> 
> > 
> 
> 
> 
> 

Good idea, let's add this

2023-10-31 07:22 UTC, bfintal commented on src/block-components/image/image.js
> +
```suggestion
```

2023-10-31 07:24 UTC, merged