fix (unique-ids): prevent unique ids from duplicating in the frontend
gambitph/Stackable pull request #2935
Opened 2023-10-18 23:55 UTC by prconcepcion

fixes #2890

2023-10-23 17:13 UTC, bfintal requested changes
A few things:

1. I recommend not using `wp_cache_set` and `wp_cache_get` here. That function is for caching things server-side and across multiple page loads.

Instead, you can just use a global PHP variable that holds all the unique ids

2. Please fix spacing issues:

``diff
- for ($i = 0; $i < $length; $i++) {
+for ( $i = 0; $i < $length; $i++ ) {
```

3. Please also adjust variable names - do not use `$test`

2023-10-26 01:29 UTC, bfintal requested changes
Some comments:

1. Looks like you're checking whether `$stackable_unique_ids` exists inside the function, you don't need to do this. You can define the variable outside the function right away:

```
$stackable_unique_ids = array();
```

2. You can access the global variable without using `$GLOBALS`

3. To make things more readable, I recommend assigning the unique id into a variable:

```php
$unique_id = isset( $block['attrs']['uniqueId'] ) ? $block['attrs']['uniqueId'] : '';
if ( empty( $unique_id ) ) {
	return $block_content;
}
```

4. Only do this for stackable blocks, so check first before if the block name starts with `stackable/` in the function

2023-10-26 01:29 UTC, bfintal commented on src/unique-id.php
> +			$string .= $characters[ mt_rand(0, strlen( $characters ) - 1) ];
`mt_rand` is not available across all web servers, please use `wp_rand` instead

2023-10-26 01:29 UTC, bfintal commented on src/unique-id.php
> +	error_log(print_r($stackable_unique_ids, true));
Please remove debugging stuff
```suggestion
```

2023-10-26 01:29 UTC, bfintal commented on src/unique-id.php
> +		$random_unique_id = stackableGetRandomString(7);
```suggestion
		$random_unique_id = stackableGetRandomString( 7 );
```

2023-10-27 00:26 UTC, bfintal requested changes
Minor tweaks

2023-10-27 00:26 UTC, bfintal commented on src/unique-id.php
> +	if ( ! is_array( $stackable_unique_ids ) ) {
Instead of checking if it's an array, it's simpler to just define it as an array outside the function.

$stackable_unique_ids = array();

2023-10-27 00:26 UTC, bfintal commented on src/unique-id.php
> +		$stackable_unique_ids = array_merge( $stackable_unique_ids, array( $random_unique_id )  );
I recommend just pushing the new value here instead of merging for readability

2023-10-27 00:26 UTC, bfintal commented on src/unique-id.php
> +	function stackable_get_random_string( $length ) {
Instead of random string, can you change this function to be stackable_generate_unique_id without the need to pass a length anymore?

2023-10-27 04:24 UTC, bfintal requested changes
Last change, please wrap `stackable_prevent_duplicate_unique_ids` in a `function_exists` check

2023-10-27 04:55 UTC, bfintal commented on src/unique-id.php
> +add_filter( 'render_block', 'stackable_prevent_duplicate_unique_ids', 9, 2 );
```suggestion
add_filter( 'render_block', 'stackable_prevent_duplicate_unique_ids', 9, 2 );
}
```

2023-10-27 08:42 UTC, andeng1106 commented
@prconcepcion @bfintal 

Remaining issue:

- If debug mode is on and you duplicate a block (stackable or native) / reusable block, a `strpos()` code error displays:

https://github.com/gambitph/Stackable/assets/103395655/47c210e8-90ef-4858-a2c6-78f222dfe924

- Please include the fix for this since it's related: https://github.com/gambitph/Stackable/issues/2822

2023-10-27 11:32 UTC, bfintal commented on src/unique-id.php
> +		if ( strpos( $block['blockName'], 'stackable/' ) === false ) {
```suggestion
		$block_name = isset( $block['blockName'] ) ? $block['blockName'] : '';
		if ( stripos( $block_name, 'stackable/' ) === false ) {
```

2023-10-27 14:25 UTC, andeng1106 commented
@prconcepcion Remaining issue for https://github.com/gambitph/Stackable/issues/2822:
- Fix is now ok for frontend but issue still exist in editor:

https://github.com/gambitph/Stackable/assets/103395655/349031b8-c348-436d-93d7-5d42471384d8

2023-10-27 14:32 UTC, bfintal commented
> @prconcepcion Remaining issue for https://github.com/gambitph/Stackable/issues/2822:
> 
> - Fix is now ok for frontend but issue still exist in editor:
> 
> 
> 
> https://github.com/gambitph/Stackable/assets/103395655/349031b8-c348-436d-93d7-5d42471384d8
> 
> 
> 
> 

Please create another issue for this new one. This PR is only for the frontend and is mainly addresses dynamically inserted blocks that can get unique id conflicts

2023-10-27 17:16 UTC, merged