fix (button): prevent block error upon adding an anchor
gambitph/Stackable pull request #3004
Opened 2023-12-11 07:07 UTC by prconcepcion

fixes #2998

2023-12-11 07:16 UTC, bfintal requested changes
I don't think this is the proper fix for this, because if you check all the other blocks, they do not declare `anchor` in their attribute list

2023-12-20 02:31 UTC, bfintal commented on src/block-components/advanced/edit.js
> +						label={ __( 'Anchor Link', i18n ) }
```suggestion
						label={ __( 'Anchor ID', i18n ) }
```

2023-12-20 02:36 UTC, bfintal requested changes
It doesn't feel right that the option for the Anchor ID is inside the Advanced block component because only the buttons are going to use it.

I suggest adding the option inside inside the button's **Style tab > Link panel** since it's related to it

2024-01-03 05:07 UTC, bfintal requested changes
When I activate the plugin, I get a space on the sidebar: 
<img width="846" alt="image" src="https://github.com/gambitph/Stackable/assets/1033611/bf01c081-fa71-426f-a28a-012e15c102b6">

2024-01-04 07:28 UTC, andeng1106 commented
> When I activate the plugin, I get a space on the sidebar: <img alt="image" width="846" src="https://private-user-images.githubusercontent.com/1033611/293837598-bf01c081-fa71-426f-a28a-012e15c102b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDgwMjksIm5iZiI6MTcwNDM0NzcyOSwicGF0aCI6Ii8xMDMzNjExLzI5MzgzNzU5OC1iZjAxYzA4MS1mYTcxLTQyNmYtYTI4YS0wMTJlMTVjMTAyYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMDU1NTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVjOWI4NzA0YmEwYTY5ZDdmZTE0MzI4M2EwNWU5NzYxY2Q4YjM1NTA1MjU3Njk2MzMwOTFlNTljNmM0MjZhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R82OvgpTpe3AiCCUfKkFB77Jwr2gGnvtpSj9D4Ai5Z4">

@bfintal I'm also seeing this when using 3.12.8 with debug mode enabled.

<img width="985" alt="Screenshot 2024-01-04 at 2 09 02 PM" src="https://github.com/gambitph/Stackable/assets/103395655/58abc1fd-460a-45cd-b969-c45ee253cbc9">

2024-01-17 06:44 UTC, merged