fix (separator): prevent bottom separator overlapping content
gambitph/Stackable pull request #3081
Opened 2024-02-27 07:08 UTC by prconcepcion

fixes #3061

2024-02-27 07:15 UTC, bfintal requested changes

2024-02-27 07:15 UTC, bfintal commented on src/block-components/separator/style.scss
> +			position: relative;
can we not place a `position: relative` here because this might cause unwanted side effects.

2024-02-27 07:56 UTC, prconcepcion commented on src/block-components/separator/style.scss
>  		.stk-separator ~ *:not(.stk-separator, .stk-video-background) {
@bfintal when I only add a top separator this rule applies that's why I thought it was fine to add that

2024-03-06 14:31 UTC, bfintal commented on src/block-components/separator/style.scss
> +		:is(.stk-block-hero__content, .stk-block-call-to-action__content) {
```suggestion
		// This is for the CTA and Hero block
		:is(.stk-block-hero__content, .stk-block-call-to-action__content) {
```

2024-03-06 14:37 UTC, bfintal commented on src/block-components/separator/style.scss
> +	&.stk-block-feature:is(.stk-has-bottom-separator) {
```suggestion
	// This is for the Feature block
	&.stk-block-feature:is(.stk-has-bottom-separator) {
```

2024-03-22 01:33 UTC, merged

2024-04-02 12:10 UTC, bfintal commented
@prconcepcion Looks like this PR has issues with regards to background tints / gradients going above the separator. The changes from this PR have been reversed from the `develop` branch. Please create a new PR with the adjusted fix