fix: Refactor usage of __unstableGetClientIdsTree
gambitph/Stackable pull request #3104
Opened 2024-03-11 11:12 UTC by mxkae

fixes #2798

2024-03-13 10:46 UTC, bfintal commented on src/plugins/get-client-id-tree/index.js
> +	}, [ blockCount ] )
Can we see if using `getClientIdsWithDescendants` will help with this?
```suggestion
	const allClientIds = useSelect( select => {
		return select( 'core/block-editor' ).getClientIdsWithDescendants()
	} )

	useEffect( () => {
		console.log('did update' )
		dispatch( 'stackable/block-editor' ).updateClientTree()
	}, [ allClientIds ] )
```

2024-03-20 06:34 UTC, mxkae commented
`blocks` in `<ListView>` is deprecated since version 6.3 as shown below so there's no need to get the inner blocks using the client tree anymore.

<img width="1271" alt="Screenshot 2024-03-20 at 2 10 14 PM" src="https://github.com/gambitph/Stackable/assets/98727316/fb7f9b02-24b4-443d-97af-fcbbf0afdd35">

2024-03-20 12:26 UTC, bfintal requested changes
Now we have 2 stores for this purpose:
1. `src/hooks/use-block-context.js`
2. `src/plugins/get-client-id-tree/store.js`

I believe both of these are used solely for updating block context, so we should be able to combine these into just one.

2024-03-22 08:12 UTC, andeng1106 commented
@mxkae Remaining issue: 
- Related to https://github.com/gambitph/Stackable/issues/2822

https://github.com/gambitph/Stackable/assets/103395655/52930abe-4f43-4e54-b8d6-2e9baac99163

2024-03-22 12:44 UTC, merged