feat (tabs block): added tab anchors
gambitph/Stackable pull request #3124
Opened 2024-04-01 07:11 UTC by mxkae

fixes #3067

2024-04-02 04:46 UTC, bfintal requested changes
Comments:
- Update the labels to be kebabCase on blur instead of timeout because if you edit the middle of the string, the cursor will jump to the end.
- The tab anchor doesn't work if linking directly from a button on the same page. e.g. if you have a button/link that links to `#tab-two`, the 2nd tab will not open when you click on the button/link

2024-04-02 04:46 UTC, bfintal commented on src/block/tab-labels/edit.js
> +									placeholder="Tab Anchor"
This needs to be translatable
```suggestion
									placeholder="Tab Anchor"
```

2024-04-02 04:46 UTC, bfintal commented on src/block/tab-labels/edit.js
> +							{ props.attributes.tabLabels.map( ( tab, index ) => (
Add a help note before the fields saying "Add unique names to each tab, so you'll be able to link directly and open each tab."

2024-04-04 06:44 UTC, bfintal requested changes
I'm setting this for QA but here are 2 comments that need to be addressed:

1. Clicking on a tab that has an anchor should not scroll the browser (to test, add a 1000px spacer block above and below the tabs block, then click on a tab that has an anchor)

2. Refreshing the browser that has a tab anchor link should scroll to the tab. Currently, the tab is open, but it doesn't scroll to it (to test, have a 1000px spacer block before the tabs block, then visit the url with the has tab hash in another window)

2024-04-04 10:19 UTC, andeng1106 commented
@mxkae some issues found:

- [ ] When typing in the tabs anchor fields, it seems laggy if I have nested blocks in the Tabs block (not sure if this is related to the Tabs slowdown?)

https://github.com/gambitph/Stackable/assets/103395655/bb7e5eb2-7ebb-4362-af2f-64c9a22ea1c8


- [ ] [Incosistent] Adding / resetting tabs anchor field sometimes doesn't register the change (Update / Save Draft button doesn't highlight)
     - Unable to figure out what's causing it and hard to catch but might be related to the Reset button. Here are some sample videos how it happens:

https://github.com/gambitph/Stackable/assets/103395655/a4b906ee-9de0-49a9-a294-c065d1ab750a


https://github.com/gambitph/Stackable/assets/103395655/8da05cc2-e201-472e-b096-2ab08a26f7a4

2024-04-12 11:51 UTC, merged