feat/3279 default block text
gambitph/Stackable pull request #3283
Opened 2024-08-08 03:25 UTC by Arukuen

fixes #3279

2024-08-08 05:04 UTC, bfintal requested changes

2024-08-08 05:04 UTC, bfintal commented on src/plugins/global-settings/editor-loader.js
> +	}
Instead of adding it here in the global settings, you can create your own "default-text-block" plugin and register it using `registerPlugin`

2024-08-15 05:25 UTC, bfintal commented on src/welcome/admin.js
> +			help={ __( 'If this is enabled, the default block when adding a new block will be the Stackable Text block.', i18n ) }
```suggestion
			help={ __( 'If enabled, Stackable Text blocks will be added by default instead of the native Paragraph Block.', i18n ) }
```

2024-08-15 07:32 UTC, andeng1106 commented
@Arukuen When copy pasting 2 or more paragraphs, the first and last block is a Text block which is correct but the blocks in the middle are Paragraph blocks instead of Text blocks.


https://github.com/user-attachments/assets/abe0fc1b-c9be-4fe2-8497-7b7fc7ca0e8c

2024-08-28 06:17 UTC, bfintal requested changes

2024-08-28 06:17 UTC, bfintal commented on src/plugins/text-default-block/index.js
> +	setDefaultBlockName( 'stackable/text' )
This might run multiple times, I believe this is a React Component

2024-08-28 06:17 UTC, bfintal commented on src/block/text/transforms.js
> +		{
```suggestion
		// When pasting, ensure that the default text block setting is followed
		{
```

2024-09-02 02:55 UTC, andeng1106 commented
@Arukuen Remaining issue:

Toggle setting disables upon refresh. Feature still works correctly but the toggle setting is showing it incorrectly.

https://github.com/user-attachments/assets/52f2e172-35c7-4af0-85b2-9f340c94e031

2024-09-05 06:50 UTC, merged